---
output:
  html_document: default
  pdf_document: default
---

# Week 13: More on interactions

> Written by Margriet Groen (partly adapted from materials developed by the PsyTeachR team a the University of Glasgow)

Interactions are ubiquitous in psychological science, which is why we’ll spend some more time building models that include interaction terms. Last week we modelled well-being as a function of screen-time (a continuous predictor) and biological sex (a categorical predictor) and their interaction. This week we’ll look at interactions between continuous predictors. 

## Lectures
The lecture material for this week follows the recommended chapters in Winter (2020) -- see under 'Reading' below -- and is presented below:

* [**More on interactions (~18 min)**](https://web.microsoftstream.com/video/9e2a9e1e-548f-492e-a529-58dc1c8490f3) 

## Reading

### Winter (2020)
[**Link**](https://eu.alma.exlibrisgroup.com/leganto/public/44LAN_INST/citation/83408786230001221?auth=SAML)

**Chapter 8** explains what interactions are and how to model and interpret them.

## Pre-lab activities
After having watched the lectures and read the textbook chapters you’ll be in a good position to try these activities. Completing them before you attend your lab session will help you to consolidate your learning and help move through the lab activities more smoothly.

### Pre-lab activity 1: Data-wrangling in R
The more you practise coding in R, the easier it will become. The RStudio interactive tutorials I mentioned in weeks 11 and 12 are an excellent place to start if you haven't engaged with those yet. 

* [**The Basics**](https://rstudio.cloud/learn/primers/1) Start here to learn how to inspect, visualize, subset and transform your data, as well as how to run code.

* [**Work with Data**](https://rstudio.cloud/learn/primers/2) Learn how to extract values form a table, subset tables, calculate summary statistics, and derive new variables.

* [**Visualize Data**](https://rstudio.cloud/learn/primers/3) Learn how to use ggplot2 to make any type of plot with your data. The tutorials on [**Exploratory Data Analysis**](https://rstudio.cloud/learn/primers/3.1) and [**Scatterplots**](https://rstudio.cloud/learn/primers/3.5) are particularly relevant.

* [**Separating and Uniting Columns**](https://rstudio.cloud/learn/primers/4.2) Here you will learn to separate a column into multiple columns and to reverse the process by uniting multiple columns into a single column. Then you'll practise your data wrangling skills on messy real world data.

* [**Join Data Sets**](https://rstudio.cloud/learn/primers/4.3) Learn how to work with relational data. Here you will learn how to augment data sets with information from related data sets, as well as how to filter one data set against another.

If you feel confident with the material covered in those tutorials the following is useful to try:

* [**Programming Basics**](https://rstudio.cloud/learn/primers/1.2) R is easiest to use when you know how the R language works. This tutorial will teach you the implicit background knowledge that informs every piece of R code.

Please note that there are often different ways to do the same or similar things in R. This means you might encounter slightly different functions or styles of coding in different materials. This is not something to worry about. Just make sure you're clear on what a bit of code achieves and choose the function/style that you feel most comfortable with.

### Pre-lab activity 2: Getting ready for the lab class
#### Remind yourself of how to access and work with the RStudio Server.

* [**Video on how to access the RStudio Server by Padraic**](https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=f4f414ff-dd5b-4301-9214-adbf009d10da)
* I highly recommend using R Projects to structure your workflow. You could create an R project for each week of the module. Have a look at section [**8 Workflow: projects**](https://r4ds.had.co.nz/workflow-projects.html) of **R for Data Science** by Hadley Wickam and Gareth Grolemund for an introduction.

#### Get your files ready
Download the [402_week13_forStudents.zip](files/week13/402_week13_forStudents.zip) file and upload it into a new folder in RStudio Server. 
